### ISSUE TITLE
WebApp-Home: Som en användare vill jag kunna se meny för kategorier

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#10]
**Tasks:**
- [ ] WebApp-Home: Mobil: Integrera den designade meny ikonen på webbsidans header.
- [ ] WebApp-Home: Mobil: Vid klick på meny ikonen ska en kategorimeny visas
- [ ] WebApp-Home: Mobil: Lägg till en stängningsikon på kategorimenyn som gör det möjligt för användaren att stänga menyn.
- [ ] WebApp-Home: Mobil: Lista kategorier med länkar i menyn enligt designskissen.
- [ ] WebApp-Home: Dator: Implementera en sidomeny för kategorier som är synlig på vänster sida av skärmen.
- [ ] WebApp-Home: Dator: Se till att menyn är responsiv och ser bra ut på olika skärmstorlekar.
- [ ] WebApp-Home:  Genomföra tester för att verifiera att menyikonen och kategorimenyn fungerar korrekt på både mobil och dator.

**Definition of done**
- [ ] Länk till menyn ska synas enligt designskiss i mobilvy och fungera.
- [ ] Fungerande stängningsikon i mobilvy enligt designskiss.
- [ ] Kategorimenyn ska vara implementerad enligt designskiss och länkar fungera. 
- [ ] Ikoner och länkar ska uppfylla testkriterierna för tillgänglighet
- [ ] Dokumentation ska finnas

**Test**
