### ISSUE TITLE
WebApp-Home: Som en användare vill jag kunna se produktnyheter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#11]
**_OBS! Denna UserStory ska använda befintliga Models/Service/Repository från Feature Products_**

**Tasks:**
- [x] WebApp-Home: Implementera en sektion på hemsidan som visar 4 kort med de senaste produkterna.
- [x] WebApp-Home: Utforma produktkorten enligt den angivna designskissen.
- [x] WebApp-Home: Skapa en länk i sektionen för produktnyheter som leder till en sida med alla nya produkter. 
**Återstår: Länka till rätt controller** 
- [x] WebApp-Home: Implementera funktionalitet så att varje produktkort är klickbart och leder till den specifika produktens detaljsida.
**Återstår: Länka till rätt controller** 
- [x] WebApp-Home: Genomföra tester för att säkerställa att produktkort visas korrekt och att länkar och ikoner fungerar som avsett.
**Återstår: Avvakta test tills länkar finns** 
- [x] WebApp-Home: Kontrollera att produktkorten och alla interaktiva element är tillgängliga för alla användare, inklusive de med funktionsnedsättningar.
**Återstår: Klick på korten kan testas ur tillgänglighetssynpunkt först när de blivit länkade** 
- [x] WebApp-Home: Hämta produktlista med kategori New Arrivals via befintliga Services (Products)
**Återstår: Invänta funktionalitet i Products** 

**Definition of done:**
- [x] Listan med produkterna i kategorin New Arrivals hämtas
- [x] De klickbara korten visas enligt designskiss och länkning fungerar. 
- [x] Tillgänglighet enligt testkriterierna för tillgänglighet

**Test**
