### ISSUE TITLE
WebApp-Cart: Som en användare vill jag dynamiskt se min varukorg

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#13]
**Tasks:**
- [x] WebApp-Cart:  Skapa en funktion som hämtar och visar produkter som har lagts till i varukorgen i realtid.
**Återstår: Hämta produkter från vart varukorgen nu sparas.**
- [x] WebApp-Cart: Säkerställ att produkterna presenteras i rätt format som specificerat i designskissen.
- [x] WebApp-Cart: Genomföra tester för att säkerställa att den dynamiska uppdateringen av varukorgen fungerar som avsett vid olika scenarier (till exempel när produkter läggs till, tas bort eller uppdateras).

**Definition of done**
- [x] Produkter i varukorgen visas enligt designskiss
- [x] Dynamisk uppdatering av saldo/antal osv fungerar.

**Test**
