### ISSUE TITLE
WebApp-Home: Som en användare vill jag kunna spara produkter till mina favoriter

### ISSUE THREAD

**Issue by DennisMikaj** [EC-rika-project/WebApp-RIKA-WIN23#14]
**Tasks:**
- [ ] WebApp-Home: Lägg till en ikon (t.ex. hjärtformad) på varje produktkort för att spara produkten i favoriter.
- [ ] WebApp-Home: Implementera logik som kontrollerar användarens inloggningsstatus när de klickar på favoritikonen. Om användaren inte är inloggad, ska de omdirigeras till inloggningssidan med en relevant meddelande (t.ex. "Logga in för att spara dina favoriter").
- [ ] WebApp-Home: Favoritmarkerad produkts id sparas i User api.

**Definition of done**
- [ ] Funktionaliteten för "Favoriter" fungerar. Inloggad användare ser tidigare sparade favoriter markerade.
