### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna ta bort, öka/minska antal varor

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#15]
**Tasks:**
- [x] WebApp-Cart: Implementera en "Ta bort"-knapp för varje produkt i varukorgen.
- [x] WebApp-Cart: Skapa knappar för att öka och minska antalet av varje produkt i varukorgen.
- [x] WebApp-Cart: Se till att dessa knappar uppdaterar den totala kostnaden i realtid.
- [x] WebApp-Cart: Implementera logik för att förhindra att antalet för en produkt minskas under 1. Om antalet produkter är 1 så är knappen för att minska produkter disabled/hidden.
- [x] WebApp-Cart: Se till att alla gränser och begränsningar för att lägga till eller ta bort produkter fungerar som avsett (felmeddelande om maxantal nått)
- [x] WebApp-Cart: Testa knapparnas funktionalitet och se till att de är lättillgängliga och användarvänliga.
- [x] WebApp-Cart: Genomföra tester för att verifiera att alla knappar fungerar korrekt under olika scenarier (till exempel när produkten inte finns i varukorgen, produkten redan är på maxantal, osv.).

**Definition of done:**
- [x] Knappar för ta bort/öka/minska syns och funktionalitet fungerar. 
- [x] Knapparna ska uppfylla testkriterierna för tillgänglighet

**Test**
Testfallsbeskrivning: Testa att användaren kan ta bort samt öka eller minska antalet varor i varukorgen och att varukorgen uppdateras korrekt.

### Testfall 1: Ta bort en produkt från varukorgen
Förutsättningar: 
- Användaren har minst en produkt i varukorgen.
- Instansiera CartController

Steg:
- Ta bort produkt ur varukorgen

Förväntat resultat:
- Produkten tas bort från varukorgen.
- Ett bekräftelsemeddelande kan visas, t.ex. "Produkten har tagits bort från din varukorg."

### Testfall 2: Öka antalet av en produkt i varukorgen
Förutsättningar:
- Användaren har minst en produkt i varukorgen.
- Instansiera CartController

Steg:
- Öka antalet på en produkt i varukorgen

Förväntat resultat:
- Antalet för produkten ska öka med ett steg (t.ex. från 1 till 2).
- Produktinformationen ska visa det uppdaterade antalet.

### Testfall 3: Minska antalet av en produkt i varukorgen
Förutsättningar:

- Användaren har minst en produkt i varukorgen med ett antal större än 1.
- Instansiera CartController

Steg:
- Minska antalet på en produkt i varukorgen

Förväntat resultat:
- Antalet för produkten ska minska med ett steg (t.ex. från 2 till 1).
- Produktinformationen ska visa det uppdaterade antalet.
