### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna se fraktkostnad

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#17]
**Tasks:**
- [x] WebApp-Cart: Implementera ett fält i användargränssnittet för att visa fraktkostnaden enligt designskiss.
- [x] WebApp-Cart: Skriv logik för att beräkna fraktkostnaden baserat på definierade regler (exempelvis vikt, destination, eller orderbelopp). Inkludera en kontroll för att se om orderbeloppet överstiger gränsen för fri frakt.
- [x] WebApp-Cart: Verifiera att fraktkostnaden visas korrekt enligt olika scenarier, inklusive olika leveransalternativ, orderbelopp och kontrollera att meddelandet om fri frakt dyker upp när det är tillämpligt. Kontrollera att användarens upplevelse är smidig och att inga fel uppstår under beräkningen.
- [x] WebApp-Cart:  Se till att fraktkostnaden och meddelandet om fri frakt är stilrena och lätta att förstå i sammanhanget av totalpriset. Implementera visuell feedback vid val av fraktalternativ och när fri frakt erbjuds.

**Definition of done**
- [x] Fält för fraktkostnad ska synas enligt designskiss.
- [ ] Beräkning av fraktkostnad ska fungera och visas korrekt enligt definerade regler. 
- [x] Det finns tydlig visuell kommunikation till kund vid uppnådd fri frakt. 

**Test**
