### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna se totalpriset för varor + frakt

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#18]
**Tasks:**
- [x] WebApp-Cart: Fält för att visa totaltpris för varor + frakt (se designskiss)
- [x] WebApp-Cart: Totalpriset uppdateras i dynamiskt efter produktantal
- [x] WebApp-Cart: Totala antalet produkter i varukorgen ska visas (se designskiss)

**Definition of done**
- [x] Fält för totalpris +frakt ska synas enligt designskiss.
- [x] Funktionalitet för dynamiskt uppdatering av priset vid interaktion ska fungera. 
- [x] Fält för antalet produkter ska synas enligt designskiss.

**Test**
