### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna stänga ner varukorgen

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#20]
**Tasks:**
- [x] WebApp-Cart: Ikon för att stänga ner varukorgen (se designskiss) 

**Definition of done:**
- [ ] Ikon ska synas enligt designskiss
- [ ] Funktionalitet för att stänga varukorgen ska fungera

**Test:**
