### ISSUE TITLE
WebApp-Cart: Som en användare vill jag mötas av en tydlig responsiv checkout

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#21]
**Tasks:**
- [x] WebApp-Cart: Skapa view för checkout
- [x] WebApp-Cart: Implementera styling efter design
- [x] WebApp-Cart: Säkerställ responsivitet för mobil, surfplatta, dator

**Definition of done**
- [x] Användaren möts av en responsiv sida som fungerar felfritt på samtliga enheter. 
- [x] Sidan ska efterlikna design skisserna. 
- [x] Sidan ska uppfylla testkriterierna för tillgänglighet

**Test**
