### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna logga in om jag har ett konto

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#22]
**Tasks:**
- [x] WebApp-Cart: Knapp för att kunna logga in om man har ett konto
- [x] WebApp-Cart: Loginknappen redirectar till "Login"

**Definition of done:**
- [x] Länk till logga in ska synas enligt designskiss och fungera.
 
**Test**
Testfallsbeskrivning: Testa att användaren kan se och använda en knapp för att logga in, och att denna omdirigerar användaren till inloggningssidan.

### Testfall 1: Klicka på logga in-knappen och verifiera omdirigering till inloggningssidan
Förutsättningar:
- Användaren är inte inloggad och har öppnat varukorgen.

Steg:
- Klicka på logga in-knappen i varukorgen.

Förväntat resultat:
- Användaren omdirigeras till inloggningssidan.
- URL
- ska ändras till den för inloggningssidan (t.ex. "/login").
- Inloggningssidan ska visa rätt fält och knapp för att logga in (t.ex. användarnamn och lösenord).

### Testfall 2: Kontrollera att logga in-knappen inte visas när användaren är inloggad
Förutsättningar:
- Användaren är inloggad.

Steg:
- Öppna varukorgen.

Förväntat resultat:
- Logga in-knappen ska inte visas i varukorgen när användaren redan är inloggad.
- Användaren ska istället se andra relevanta knappar, som exempelvis "Gå till kassan".
