### ISSUE TITLE
WebApp-Cart: Som en inloggad användare vill jag få automatiskt genererade personuppgifter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#23]
**Tasks:**
- [ ] WebApp-Cart: "User" hämtas från Session
- [ ] WebApp-Cart: Uppgifter från "user" används för att hämta registrerade personuppgifter från User api
- [ ] WebApp-Cart: Inloggad användare: registrerade personuppgifter visas förifyllt i ett formulär
- [ ] WebApp-Cart: Fält för förnamn, efternamn, epost

**Definition of done**
- [ ] Personuppgifterna kan visas förifyllt i formuläret.
