### ISSUE TITLE
WebApp-Cart: Som en inloggad användare vill jag få automatiskt genererade adressuppgifter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#24]
**Tasks:**
- [ ] WebApp-Cart: "User" hämtas från Session
- [ ] WebApp-Cart: Uppgifter från "user" används för att hämta registrerade adressuppgifter från User api
- [ ] WebApp-Cart: Inloggad användare: registrerade adressuppgifter visas förifyllt i ett formulär
- [ ] WebApp-Cart: Fält för gatuadress, postnummer, stad, telefonnummer

**Definition of done:**
- [ ] Adressuppgifterna kan visas förifyllt i formuläret.

**Test**
