### ISSUE TITLE
WebApp-Cart: Som en ej inloggad användare vill jag kunna fylla i mina personuppgifter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#25]
**Tasks:**
- [x] WebApp-Cart: Formulär ska visas där användaren kan fylla i sina personuppgifter
- [x] WebApp-Cart: Fält för förnamn, efternamn, epost

**Definition of done:**
- [ ] Formulär ska synas med de tre önskade fälten.
