### ISSUE TITLE
WebApp-Cart: Som en ej inloggad användare vill jag kunna fylla i mina adressuppgifter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#26]
**Tasks:**
- [x] WebApp-Cart: Formulär ska visas där användaren kan fylla i sina adressuppgifter
- [x] WebApp-Cart: Fält för gatuadress, postnummer, stad, telefonnummer

**Definition of done:**
- [ ] Formulär ska synas med de fyra önskade fälten. 

**Test**
