### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna hantera mina produkter jag har i varukorgen/checkout

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#27]
Gäller Checkout view
**Tasks:**
- [x] WebApp-Cart: Varukorgens produkter visas i en lista (se designskiss)
- [x] WebApp-Cart: Knapp för att ta bort produkt
- [x] WebApp-Cart: Knappar för öka/minska antal
- [x] WebApp-Cart: Antalet kan max minskas till 1

**Definition of done**
- [x] Produkter i varukorgen visas enligt designskiss
- [x] Funktionalitet för att öka/minska/ta bort varuantal/varor ska fungera
