### ISSUE TITLE
WebApp-Cart: Som en användare vill jag kunna se en sammanställning av orders delsummor

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#32]
**Tasks:**
- [x] WebApp-Cart: 3 Fält för att tydligt visa orderns olika totalpriser (varornas total, fraktkostnad, order total)
- [x] Implementera funktionalitet

**Definition of done:**
- [x] Fält för totalpriser ska synas enligt designskiss.
- [x] Funktionalitet för dynamiskt uppdatering av priset vid interaktion ska fungera.

**Test**
