### ISSUE TITLE
WebApp: SignUp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#34]
- [ ] EC-rika-project/dummie-repo#140
- [ ] EC-rika-project/dummie-repo#141
- [ ] EC-rika-project/dummie-repo#142
- [ ] EC-rika-project/dummie-repo#143
- [ ] EC-rika-project/dummie-repo#144
 

- [ ] EC-rika-project/dummie-repo#152
- [ ] EC-rika-project/dummie-repo#153

- [ ] EC-rika-project/dummie-repo#154

**Aktivitetsdiagram Feature**
![Image](https://github.com/user-attachments/assets/007947ea-18fe-48a0-b892-d9e975b7437e)
