### ISSUE TITLE
WebApp: Profile

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#36]
- [ ] EC-rika-project/dummie-repo#78
- [ ] EC-rika-project/dummie-repo#79
- [ ] EC-rika-project/dummie-repo#80
- [ ] EC-rika-project/dummie-repo#81
- [ ] EC-rika-project/dummie-repo#82
- [ ] EC-rika-project/dummie-repo#83
- [ ] EC-rika-project/dummie-repo#85
- [ ] EC-rika-project/dummie-repo#86
- [ ] EC-rika-project/dummie-repo#157
