### ISSUE TITLE
WebApp: Products

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#37]
- [ ] EC-rika-project/dummie-repo#64
- [ ] EC-rika-project/dummie-repo#47
- [ ] EC-rika-project/dummie-repo#48 
- [ ] EC-rika-project/dummie-repo#49 
- [ ] EC-rika-project/dummie-repo#50 
- [ ] EC-rika-project/dummie-repo#51
- [ ] EC-rika-project/dummie-repo#52
- [ ] EC-rika-project/dummie-repo#63
- [ ] EC-rika-project/dummie-repo#65
- [ ] EC-rika-project/dummie-repo#156
