### ISSUE TITLE
WebApp: SignIn

### ISSUE THREAD

**Issue by pingis00** [EC-rika-project/WebApp-RIKA-WIN23#38]
- [x] EC-rika-project/WebApp-RIKA-WIN23#56
- [x] EC-rika-project/WebApp-RIKA-WIN23#52
- [x] EC-rika-project/WebApp-RIKA-WIN23#53
- [x] EC-rika-project/WebApp-RIKA-WIN23#54
- [x] EC-rika-project/WebApp-RIKA-WIN23#55
- [x] EC-rika-project/WebApp-RIKA-WIN23#58
- [x] EC-rika-project/WebApp-RIKA-WIN23#59
