### ISSUE TITLE
WebApp: Home

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#4]
- [ ] EC-rika-project/dummie-repo#59
- [ ] EC-rika-project/dummie-repo#66
- [ ] EC-rika-project/dummie-repo#67
- [ ] EC-rika-project/dummie-repo#68
- [ ] EC-rika-project/dummie-repo#69
- [ ] EC-rika-project/dummie-repo#204
