### ISSUE TITLE
Uppsättning WebApp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#40]
**Tasks:**
- [x]  Skapa GitHub-repo
- [x]  Sätt upp projekt inklusive mappstruktur
- [x] Skapa main branch
- [x] Skapa dev branch
