### ISSUE TITLE
WebApp-Products: Som en användare vill jag kunna lämna en recension på en produkt.

### ISSUE THREAD

**Issue by AnnSofieSj** [EC-rika-project/WebApp-RIKA-WIN23#47]
**Task:**
- [ ] WebApp - Products: Skapa ett formulär för att lämna recensioner i backend. 
- [ ] WebApp - Products: Implementera metoder i ASP.NET (Controller & Services) för att hantera användarinteraktioner med recensioner. 
- [ ] WebApp - Products: Implementera logik för att spara recensioner, hantera POST-förfrågan till en produkt databas.
- [ ] WebApp - Products: Skapa ett formulär där användaren kan ange sitt betyg (1-5 stjärnor, kommentar, namn och datum i ex. ProductDetails.cshtml.
- [ ] WebApp - Products: Visa recensioner på produktsidan i samma vy som produkten visas, visa en lista över alla recensioner som lämnats av andra användare.
- [ ] WebApp - Products: Validera att betyg är mellan 1 och 5 men recensionstexten kan vara tom(?).
- [ ] WebApp - Products: Autentisera att endast inloggade användare kan lämna en recension, om användaren inte är inloggad, omdirigera till inloggningssidan.
- [ ] WebApp - Products: Enhetstesta för recension-funktionalitet så att recensioner sparas korrekt och felhantering fungerar.

- [ ] WebApp - Products: Databas recensionstabell
Recensions-ID
Produkt-ID
Användar-ID
Betyg (1-5)
Recensionstext (nullable)
Datum då recension skapades

**Definition of done:**
- [ ] En inloggad användare ska kunna lämna en recension på en eller flera produkter i form av text och stjärnor. 
- [ ] Recensionen ska sparas i produktdatabasen.
- [ ] API ska returnera ok eller felmeddelande.
