### ISSUE TITLE
WebApp-Products: Som användare vill jag kunna lägga till produkter i önskelista

### ISSUE THREAD

**Issue by LucasWictor** [EC-rika-project/WebApp-RIKA-WIN23#49]
**Tasks**
- [ ] WebApp-Products-Task: I listvyn ska man kunna klicka på ett hjärta i övre högra hörnet av en produktbild för att spara produkten till önskelistan. 
- [ ] WebApp-Products-Task:  I den detaljerade vyn ska man kunna klicka på ett hjärta på produktbilden för att spara produkten till önskelistan.  
- [ ] Implementera logik för att spara ner ProduktID (hela objektet?) med användarID i en databas.

**Definition of done:**

- [ ] Det fungerar att lägga till produkt från list-vyn.
- [ ] Det fungerar att lägga till produkt från den detaljerade vyn.
- [ ] Om det inte är statusmeddelande 200 så visas ett felmeddelande.
