### ISSUE TITLE
WebApp: Cart

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#5]
Cart:
- [ ] EC-rika-project/dummie-repo#87
- [ ] EC-rika-project/dummie-repo#88
- [ ] EC-rika-project/dummie-repo#89
- [ ] EC-rika-project/dummie-repo#90
- [ ] EC-rika-project/dummie-repo#91
- [ ] EC-rika-project/dummie-repo#92
- [ ] EC-rika-project/dummie-repo#93
- [ ] EC-rika-project/dummie-repo#94

Checkout:
- [ ] EC-rika-project/dummie-repo#95
- [ ] EC-rika-project/dummie-repo#96
- [ ] EC-rika-project/dummie-repo#97
- [ ] EC-rika-project/dummie-repo#98
- [ ] EC-rika-project/dummie-repo#99
- [ ] EC-rika-project/dummie-repo#100
- [ ] EC-rika-project/dummie-repo#101
- [ ] EC-rika-project/dummie-repo#102
- [ ] EC-rika-project/dummie-repo#103
- [ ] EC-rika-project/dummie-repo#104
- [ ] EC-rika-project/dummie-repo#106
- [ ] EC-rika-project/dummie-repo#107
- [ ] EC-rika-project/dummie-repo#108
