### ISSUE TITLE
WebApp-Products: Som användare vill jag kunna se detaljerad information om varje produkt tex pris och beskrivning

### ISSUE THREAD

**Issue by LucasWictor** [EC-rika-project/WebApp-RIKA-WIN23#51]
**Tasks:**
- [ ] WebApp-Products: Implementera funktioner för Controller för att hämta en specifik produkt med ID med GetOne() från Produkt API:et.
- [ ] WebApp-Products: Implementera funktioner för Service för att hämta en specifik produkt med ID med GetOne() från Produkt API:et.

**Definition of done:**

- [ ] När all data för en produkt hämtas ut korrekt med ID så visas en overlay med den detaljerade informationen om produkten.
- [ ] När statusmeddelande är annat än 200 så visas ett felmeddelande.
