### ISSUE TITLE
WebApp-Products: Som en användare vill jag kunna läsa andras recensioner.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#60]
**Tasks**
- [ ] WebApp-Products-Task: Implementera metod för att hämta recensioner från databasen. T.ex en Service (ex `ProductReviewService`) för att hämta alla recensioner för en specifik produkt.

- [ ] WebApp-Products-Task: Skapa en metod i controller (ex `ProductController`) som integrerar med Services (ex `ProductReviewService` för att hämta recensioner för en specifik produkt från databasen och sedan skickas till vyn med hjälp av en ViewModel (ex `ProductDetailsViewModel`). 

- [ ] WebApp-Products-Task: Lägg till stöd för att sortera recensioner efter datum (nyaste först) och högsta/lägsta betyg genom att ex utöka (ex `ProductReviewService`) med en (ex `sortOrder`).

- [ ] WebApp-Products-Task: Razor-vyn (ex` ProductDetails.cshtml`) som tar emot data från `ProductController`  ska kunna visa recensionerna som skickas i (ex `ProductDetailsViewModel`) och erbjuda en dropdown meny eller liknande för att välja sorteringsordning samt för varje recension, visa användarens betyg, textrecension (om den finns), datum och eventuellt användarnamn.

- [ ] WebApp-Products-Task:  Skriv enhetstester och integrationstester för att säkerställa att recensioner hämtas korrekt från databasen och visas korrekt i vyn.

- [ ] WebApp-Products-Task: Testa att sorteringsfunktionaliteten i frontend fungerar som förväntat och att recensioner visas i rätt ordning baserat på användarens val.

**Question to be answered**
- [ ] Fråga: Ska man omdirigeras till en ny sida tex: /reviews?{productId} när man klickar på stjärnorna från den detaljerade vyn? Eller ska man tas till ännu en overlay? Det finns inget sätt att ta sig till en sida för att filtrera och söka på recensioner.

**Definition of done**
- [ ] Man kan se andra användares recensioner som ett sammanlagt betyg på den detaljerade produktsidan samt hur många som recenserat produkten.
- [ ] Man kan gå in och läsa alla recensioner kopplade till en viss produkt genom att klicka på stjärnorna från den detaljerade vyn.
- [ ] På varje recension ska det framgå vem som skrivit den (namn), profilbild ska visas, när recensionen skrivits, betyg från 1-5, och i det fall användaren skrivit en recensionstext ska denna också visas.
- [ ] Man ska kunna filtrerar vilka recensioner man vill läsa bland annat på antalet stjärnor, datum etc.
