### ISSUE TITLE
WebApp-Products: Som en användare vill jag mötas av en snygg och responsiv design

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#61]
**Tasks:**
- [x] WebApp-Products: Skapa en View som heter Products.cshtml.
- [x] WebApp-Products: HTML och CSS utifrån design på sidan för alla produkter.
- [x] WebApp-Products: Skapa en View som heter ProductDetails.cshtml.
- [x] WebApp-Products: HTML och CSS utifrån design på sidan för detaljerad vy.
- [x] WebApp-Products: Säkerställ responsivitet för mobil, surfplatta och dator. 

**Definition of done:**

- [x] Jag möts av en snygg design som stämmer överens med designmallen.
- [x] Sidan är responsiv för mobil. 
- [x] Sidan är responsiv för surfplatta. 
- [x] Sidan är responsiv för dator. 
- [x] Alla elementen listas upp korrekt och data hämtas från API.
- [x] Sidan är tillgänglighetsanpassad.

 **Test case descriptions**
