### ISSUE TITLE
WebApp-Products: Som en användare vill jag kunna se lagerstatus för varje produkt.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#62]
**Tasks:**
- [ ] WebApp-Products: Knyta ett HTML element till saldo från databasen där produktens lagerstatus visas.
- [ ] WebApp-Products: 3 olika lagerstatus: Avaliable in stock, Few in stock, Out of stock. Där fåtal i lager visas om mindre än 10 (?).
- [ ] WebApp-Products: Vid Out of stock ska knappen för köp inaktiveras, samt fält för att ange mailadressen visas för att få mail då varan åter finns i lager. 

**Question to be answered**
- [ ] När ska saldo uppdateras i databasen? När produkt läggs till i varukorg? när man checkar ut en varukorg? när ordern skickas?

**Definition of done:**
- [ ] En produkt går inte att lägga till i varukorgen om den inte är i lager.
- [ ] Lagerstatus uppdateras när sidan laddas om.
- [ ] Lagersaldo framgår klart och tydligt på den detaljerade produktsidan.
