### ISSUE TITLE
WebApp-Profile: Som användare vill jag kunna se en lista över tidigare och nuvarande beställningar.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#65]
**Tasks:**
- [ ] WebApp-Profile-Task: Skapa en metod i en serviceklass (ex `OrderService`) som hämtar alla tidigare och nuvarande beställningar för en specifik användare baserat på användarens ID som retunerar en lista över produkt-ID.

- [ ] WebApp-Profile-Task: Skapa en metod i controller (ex `ProfileController` eller `OrderController` som använder `OrderService` för att hämta användarens beställningar och skicka till vyn via en ViewModel (ex `UserOrdersViewModel`).
 Metoden bör även hantera eventuell felhantering (om användaren inte har några beställningar eller om något går fel i databasåtkomsten.

- [ ] WebApp-Profile-Task: Skapa ViewModel  (ex `UserOrdersViewModel`) som innehåller de ID som representerar relationerna (`UserId`, `OrderId`, `productId`) och eftersom du endast sparar ID, kommer du behöva loopa ut dessa i vyn när mer detaljer om produkten behövs (t.ex. produktnamn, pris) kan dessa hämtas från databasen via deras ID. 

- [ ] WebApp-Profile-Task:  Säkerställ att endast inloggade användare kan se sina beställningar och kontrollera att användarens ID matchar den som äger beställningarna.

- [ ] WebApp-Profile-Task: Skriv enhetstester och integrationstester för att säkerställa att beställningar hämtas (`OrderService`) korrekt och att `ProfileController` leverar rätt data till vyn.

- [ ] WebApp-Profile-Task: Testa att beställningslistan visas korrekt i frontend (ex `OrderHistory.cshtml`).

**Definition of done:**

- [ ] Den inloggade användaren kan få upp en lista på sina nuvarande beställningar.
- [ ] Den inloggade användaren kan få upp en lista på sina tidigare beställningar.
- [ ] Den inloggade användaren ska i dessa listor kunna se produktnamn, produktbild, produktpris och beställningsdatum.
- [ ] Den inloggade användaren ska kunna se meddelande om man inte har några beställningar.
- [ ] Den inloggade användaren ska kunna se felmeddelande om listorna inte kan hämtas från API.
- [ ] Användare möts av en väldesignad och tydlig sida med bra tillgänglighet.
- [ ] Sidan fungerar bra i mobilt läge.
- [ ] Sidan fungerar bra i surfplatte läge.
- [ ] Sidan fungerar bra i desktop läge.
