### ISSUE TITLE
WebApp-Profile: Som användare vill jag kunna ändra inställningar i appen som tex dark/light mode, språk och notifikationer.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#67]
**Tasks:**

**Dark/light Mode**
- [ ] WebApp-Profile-Task: Implementera ex: ett formulär med html/css för att användaren ska kunna klicka i checkbox och välja mellan dark /light mode.
- [ ] WebApp-Profile-Task: Implementera logik för att hantera bool värdet från checkboxen och koppla det till en cookie.
- [ ] WebApp-Profile-Task: Implementera logik för att hämta upp cookie information och igenom söka efter rätt key:value pair och hantera vilket färgschema man som användare ska mötas av i appen.

**Språkval**
- [ ] WebApp-Profile-Task: Implementera ex: ett flervalsformulär med html/css för att användaren ska kunna välja mellan olika språk.
- [ ] WebApp-Profile-Task: Implementera logik för att hantera värdet från formuläret och koppla det till en cookie.
- [ ] WebApp-Profile-Task: Implementera logik för att hämta upp cookie information och igenom söka efter rätt key:value pair och hantera vilket språk man som användare ska mötas av i appen.

**Notiser**
- [ ] WebApp-Profile-Task: Implementera ex: ett formulär html/css för att användaren ska kunna välja hur de ska få notiser
- [ ] WebApp-Profile-Task: Implementera logik för att hantera värdena från formuläret och koppla det till en cookie.
- [ ] WebApp-Profile-Task: Implementera logik för att hämta upp cookie information och igenom söka efter rätt key:value pair och hantera vilka notiser man som användare ska mötas av i appen.

**Definition of done**
- [ ] Användaren kan skifta mellan dark / light mode via en checkbox.
- [ ] När användaren återvänder till sidan kommer applikationen ihåg deras val.
- [ ] Användaren kan välja hur de vill få notiser
- [ ] En cookie-popup visas första gången användaren besöker sidan, där de kan acceptera alla cookies eller välja vilka cookies de vill tillåta.
- [ ] Dokumentation finns om hur sidan hanterar sina cookie-inställningar och vad varje val innebär.
- [ ] nvändaren kan välja mellan olika språk och alla texter översätts korrekt baserat på val och är konsekventa genom hela sidan.

**Comment by alenagicic** [comment]
Syfte: Verifiera att användaren kan ändra inställningar i appen, som dark/light mode, språk och notifikationer.

Förutsättningar:
    Användaren är inloggad och har tillgång till profilsidan.  Fälten för dark/light, språk och notifikationer är hämtat från sparad Cookie och 
    är förifyllt.

Teststeg:
    Acceptera eventuella cookies.
    Navigera till profilsidan.
    Ändra värdena i fälten för dark/light, språk och notifikationer.
    Ladda om sidan för att kontrollera att ändringarna sparats korrekt.

Förväntat resultat:
    Uppgifterna är oförändrade även efter sidomladdning.
    Säkerställ att ändringen av ändringarna verkligen "slår igenom" när användaren trycker på knapparna.

Fel scenario:
   Misslyckad hämtning av cookiedata
   Misslyckad sparning av uppdaterade användaruppgifter.


Utfallsstatus: Pass / Fail
