### ISSUE TITLE
WebApp-Profile: Som användare vill jag kunna lägga till och ändra leveransaddress

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#68]
**Tasks:**
- [ ] WebApp-Profile: Skapa ett formulär för leveransadress som kopplas till en ViewModel och dto. 
- [ ] WebApp-Profile: Validering av dto med DataAnnotations och JavaScript i frontend. 
- [ ] WebApp-Profile: Implementera funktion i en AccountController för att hämta nuvarande leveransadress från API om det finns någon.
- [ ] WebApp-Profile: Implementera funktion i en AccountController för att uppdatera nuvarande leveransadress i API om det finns någon.

**Definition of done:**
- [ ] Leveransadressen sparas in korrekt i databasen.
- [ ] Leveransadressen uppdateras i databasen när användaren gör en ändring och trycker på spara i formuläret. 
- [ ] Leveransadress som redan finns sparad visas i frontend.
- [ ] Leveransadressen kan inte vara tom.
- [ ] Meddelande visas när ny adress sparas korrekt.
- [ ] Felmeddelande om ny adress inte kan sparas.
- [ ] Felmeddelande om nuvarande adress inte kan hämtas från API.

**Comment by DennisMikaj** [comment]
Testfall: Leveransadressformulär och validering

Användarberättelse:  WebApp-Profile: Skapa ett formulär för leveransadress som kopplas till ev ViewModel och DTO. Validering av DTO med DataAnnotations och JavaScript i frontent. Implementera funtion AccountController för att hämta och uppdatera nuvarande leveransadress.

Syfte: Verifiera att formuläret för leveransadress fungerar korrekt, inklusive visning, validering och API-integration.

Förutsättningar:
         Användaren är inloggad, har tillgång till profilsidan och kommer åt sidan där leveransadress ändras. 

Teststeg:
Navigera till profilsidan.
Navigera till Settings.
Kontrollera att all data hämtas ifrån API och populerar formulärets fält.
Validera formuläret 
- Lämna alla fält tomma och försök skicka in formuläret
- Fyll i fälten med ogiltig data (ex. felaktigt postnummer) 
- Klicka på "Spara" och kontrollera att felmeddelanden visas korrekt.

Uppdatera leveransadressen
- Fyll i formuläret med en ny leveransadress
- Klicka på "Spara" och observera eventuelle meddelanden.
- Kontrollera att den uppdaterade informationen sparas korrekt i databasen.
- Kontrollera att meddelande för lyckad uppdatering visas korrekt.

Förväntat resultat:
- Formulären populeras med data ifrån API.
- Uppdaterad information sparas korrekt.
- Rätt meddelande visas vid både lyckad och misslyckad uppdatering av adress.

Fel scenario:
- Formuläret visar ingen data när sidan laddas
- Formuläret visar fel data när sidan laddas
- Formuläret går inte att uppdatera/spara.
- Felmeddelanden visas ej vid tomma eller felaktigt ifyllda fält.


Utfallsstatus: Pass / Fail
