### ISSUE TITLE
WebApp-Home: Som en användare vill jag mötas av en snygg responsiv sida

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#7]
**Task:**
- [x] WebApp-Home: Utveckla en vy för hemsidan med relevanta komponenter och innehåll.
- [x] WebApp-Home: Implementera styling efter design.
- [x] WebApp-Home: Testa och optimera sidan för att säkerställa att den ser bra ut och fungerar smidigt på mobil, surfplatta, dator. 
- [x] WebApp-Home: Se till att alla bilder är optimerade för snabb laddning och bra kvalitet på olika enheter.
- [x] WebApp-Home: Implementera tillgänglighetsstandarder för att säkerställa att sidan är användbar för alla, inklusive personer med funktionsnedsättningar.

**Definition of done**
- [x] Användaren möts av en responsiv sida som fungerar felfritt på samtliga enheter. 
- [x] Sidan ska efterlikna design skisserna. 
- [x] Sidan ska uppfylla testkriterierna för tillgänglighet

**Test**
