### ISSUE TITLE
WebApp-Profile: Som användare vill jag kunna läsa RIKAs Privacy Policy.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#70]
**Tasks:**

- [ ] WebApp-Profile-Task: Implementera HTML/CSS för en knapp som när den trycks på öppnar RIKAs Privacy Policy.
- [ ] WebApp-Profile-Task: Implementera logik för att hämta RIKAs Privacy policy.
- [ ] WebApp-Profile-Task: Implementera logik för att visa RIKA's Privacy policy.

*Förslag:*
Detta kan för enkelhets skull ligga som ett enskilt dokument Pdf dokument i projektappen eller i infrastructure. (Kräver ganska så lite logik, huvudsakligen en a-länk till pdf på servern (som ska öppnas i en ny länk?).)
Det kan alternativt ligga som ett Objekt som mappas ut i html där man i klassen skriver texten på varje prop från början. (kräver html/css och logik)
Det kan alternativt sparas ner i databas som ett json objekt och hämtas via API. (kräver ännu mer html/css och logik)

Diskutera och kom fram till ett svar.

**Definition of done:**
- [ ] Användare kan klicka på en knapp för att visa RIKAs Privacy policy.

**Comment by alenagicic** [comment]
Syfte: Verifiera att användaren kan läsa RIKAS privacy policy.

Förutsättningar:
    Användaren är inloggad och har tillgång till profilsidan/privacy policy.

Teststeg:
    Navigera till Privacy policy.
    Klicka på Privacy policy.
    Bekräfta att länken öppnas i samma fönster eller en ny flik.

Förväntat resultat:
    Privacy Policy-dokumentet visas korrekt och är lättläst.
    Innehållet i Privacy Policy ska vara tydligt och följa gällande lagar om dataskydd (t.ex. GDPR).
    Användaren ska kunna scrolla genom dokumentet utan problem.

Fel scenario:
   Innehållet laddas ej
   Innehållet går att tyda
   

Utfallsstatus: Pass / Fail
