### ISSUE TITLE
WebApp-SignUp:  Som en användare vill jag kunna välja användarnamn.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#72]
**Task:**
- [ ] WebApp-SignUp: Användarnamnet måste vara unikt och inte redan finnas registrerat.
- [ ] WebApp-SignUp: Validering av användarnamn(regex, min 2 tecken).
- [ ] Tempdata ska finnas om användarnamn är giltigt eller ogiltigt.

**Definition of done:**

- [ ] Logik för validering. 
- [ ] Logik för att användarnamn måste vara unikt.
- [ ] Tempdata ska finnas om användarnamn är giltigt eller ogiltigt.

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/1c05fd82-e9c0-4aea-b55f-6b811a25e2d8)
