### ISSUE TITLE
WebApp-SignUp:  Som en användare vill jag kunna välja email address.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#73]
**Task:**
- [x] WebApp-SignUp: Email måste vara unikt och inte redan finnas registrerat.
- [x] WebApp-SignUp: Validering av email ska finnas (regex).
- [x] Tempdata ska finnas för om email är giltigt eller ogiltigt

**Exempel på regex**
[RegularExpression(@"^[a-zA-Z0-9._%+-]{1,}@[a-zA-Z0-9.-]{2,}\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email address")]

**Definition of done:**

- [x] Logik för att validera email.
- [x] Logik för att email måste vara unikt.
- [x] Tempdata ska finnas för om email är giltigt eller ogiltigt

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/ca850dce-5373-44e8-a873-52b6a8248ea8)

**Test:**

_Beskrivning_: Säkerställ att e-postadressen valideras enligt regex-regler, är unik och att Tempdata används för att indikera giltig eller ogiltig e-postadress.

_Förutsättningar:_Användaren befinner sig på registreringssidan och en användare med e-postadressen "test@test.com" redan finns registrerad.

_Steg & Förväntade Resultat:_

1. **Validering av felaktigt e-postformat:**
- Ange en ogiltig e-postadress som bryter mot regex-regeln (t.ex. "test@test").
- Klicka på "Registrera".
- Förväntat resultat: Ett felmeddelande visas, t.ex. "Ogiltig e-postadress".
- Tempdata: Lagrar att e-postadressen är ogiltig.

2. **Kontrollera unikt e-postadress:**
- Ange "test@test.com" som e-postadress.
- Klicka på "Registrera".
- Förväntat resultat: Ett felmeddelande visas som informerar att e-postadressen redan är upptagen.
- Tempdata: Lagrar att e-postadressen är ogiltig.
- 

3. **Ange en giltig och unik e-postadress:**
- Ange en giltig e-postadress som uppfyller regex-regeln och inte finns registrerad.
- Klicka på "Registrera".
- Förväntat resultat: E-postadressen sparas, användaren registreras framgångsrikt utan felmeddelanden.
- Tempdata: Lagrar att e-postadressen är giltig.
