### ISSUE TITLE
WebApp-SignUp: Som en användare vill jag ha en tydlig och användarvänlig design på sign up sidan, så att det är enkelt att skapa ett konto och navigera.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#74]
**Task:**
- [ ] WebApp-SignUp: Skapa en formulärstruktur för inloggningsuppgifter.
- [ ] WebApp-SignUp: Skapa ett fält för användarnamn.
- [ ] WebApp-SignUp: Skapa ett fält för email address.
- [ ] WebApp-SignUp: Skapa ett fält för lösenord.
- [ ] WebApp-SignUp: Skapa ett fält för att bekräfta lösenord.
- [ ] WebApp-SignUp: Skapa en klickbar ruta för användarvillkor.
- [ ] WebApp-SignUp: Skapa en knapp för att signa upp.
- [ ] WebApp-SignUp: Sidan ska vara responsiv och anpassad för mobile layout.
- [ ] WebApp-SignUp: Sidan ska vara responsiv och anpassad för tablet layout.
- [ ] WebApp-SignUp: Sidan ska vara responsiv och anpassad för desktop layout.

**Definition of done:**

- [ ]  Användaren möts av en sida med tydlig design och användargränssnitt.
- [ ] Sidan ska vara anpassad för mobile layout.
- [ ] Sidan ska vara anpassad för tablet layout.
- [ ] Sidan ska vara anpassad för desktop layout.

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/aabda1d0-491a-46ae-8d06-07ebc55504eb)
