### ISSUE TITLE
WebApp: SignUp-Som en användare vill jag kunna bekräfta mitt lösenord.

### ISSUE THREAD

**Issue by adyplin** [EC-rika-project/WebApp-RIKA-WIN23#75]
**Task:**
- [x] WebApp-SignUp: Validering för bekräfta lösenord ska finnas (regex, minst en stor bokstav, en liten bokstav, en siffra och ett tecken)
- [x] WebApp-SignUp: Lösenord och bekräfta lösenord måste stämma överens med varandra.

**Exempel på regex**
[RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^a-zA-Z\\d]).{8,}$", ErrorMessage = "Invalid password format")]

**Definition of done:**

- [x] När validering finns.
- [x] När logik för att lösenord och bekräfta lösenord finns.
- [x] Tempdata ska finnas för om bekräfta lösenord är giltigt eller ogiltigt

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/634fa99c-8015-45ba-9bae-51a68e416348)

**Test:**

Beskrivning: Säkerställ att lösenordet valideras enligt regex-krav, att lösenord och "bekräfta lösenord" överensstämmer och att Tempdata används för att indikera giltigt eller ogiltigt lösenord.

_Förutsättningar:_ Användaren är på registreringssidan.

_Steg & Förväntade Resultat:_

1. Validera lösenordskrav:

- Ange ett lösenord som inte uppfyller regex-kraven (t.ex., endast små bokstäver).
- Förväntat resultat: Ett felmeddelande visas som anger att lösenordet måste innehålla minst en stor bokstav, en liten bokstav, en siffra och ett specialtecken, samt vara minst 8 tecken långt.
- Tempdata: Lagrar att lösenordet är ogiltigt.

2. Kontrollera matchande lösenord: 

- Ange ett giltigt lösenord i "Lösenord"-fältet och ett annat lösenord i "Bekräfta lösenord"-fältet.
- Förväntat resultat: Ett felmeddelande visas som anger att lösenorden inte överensstämmer.
- Tempdata: Lagrar att lösenordet är ogiltigt.

3. Ange ett giltigt och matchande lösenord:

- Ange ett giltigt lösenord som uppfyller alla krav och skriv samma lösenord i "Bekräfta lösenord"-fältet.
- Förväntat resultat: Lösenordet sparas, och användaren kan fortsätta registreringen utan felmeddelanden.
- Tempdata: Lagrar att lösenordet är giltigt.
