### ISSUE TITLE
WebApp: SignUp-Som en användare vill jag ha en knapp så jag kan signa upp efter att jag har fyllt i mina uppgifter.

### ISSUE THREAD

**Issue by adyplin** [EC-rika-project/WebApp-RIKA-WIN23#77]
**Task:**

- [x] Skapa en knapp "Sign up" för att slutföra skapande av konto.
- [ ] Användarinformationen ska skickas till Api: Users.
- [x] WebApp-SignUp: När användaren är skapad ska den bli omdirigerad till sign in sidan.

**Definition of done:**

- [x] Användarinformationen ska komma in till Api: Users.
- [x] Användaren ska bli omdirigerad till sign in sidan.

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/c62acc7f-31e4-4e20-ba5a-fb1d2fb89596)

**Test:**

_Beskrivning_: Säkerställ att en användare kan fylla i sina uppgifter, skapa ett konto, och att användaren omdirigeras till sign in sidan.

_Förutsättningar_: Användaren befinner sig på registreringssidan.

_Steg & Förväntade Resultat:_

1. **Fyll i korrekta uppgifter och godkänn villkoren::**
- Ange ett giltigt användarnamn, lösenord och e-post, och klicka i att du godkänner villkoren.
- Förväntat resultat: Du kan trycka på knappen "Sign Up".

2. **Fyll i ofullständiga eller felaktiga uppgifter:**
- Lämna något fält tomt eller ange en ogiltig e-postadress.
- Förväntat resultat: Ett felmeddelande visas som säger "Kontrollera dina uppgifter,"

3. **Skapa konto med komplett och korrekt information:**
- Klicka på knappen "Sign Up" när alla fält är korrekt ifyllda.
Förväntat resultat: Ett konto skapas, och ett meddelande visas som bekräftar att kontot har skapats ("Konto skapat").

4. **Kontroll av omdirigering**
- Efter att kontot har skapats, kontrollera att användaren omdirigeras till "sign in" sidan.
- Förväntat resultat: Användaren omdirigeras automatiskt till sign in.
