### ISSUE TITLE
WebApp: SignUp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#81]
- [ ] EC-rika-project/WebApp-RIKA-WIN23#74
- [ ] EC-rika-project/WebApp-RIKA-WIN23#72
- [ ] EC-rika-project/WebApp-RIKA-WIN23#80
- [ ] EC-rika-project/WebApp-RIKA-WIN23#73
- [ ] EC-rika-project/WebApp-RIKA-WIN23#79
 

- [ ] EC-rika-project/WebApp-RIKA-WIN23#75
- [ ] EC-rika-project/WebApp-RIKA-WIN23#78

- [ ] EC-rika-project/WebApp-RIKA-WIN23#77

**Aktivitetsdiagram Feature**
![Image](https://github.com/user-attachments/assets/007947ea-18fe-48a0-b892-d9e975b7437e)
