### ISSUE TITLE
Project:  Skapa grund css

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#84]
**Tasks:**

- [x]  Skapa grundläggande CSS-klasser
- [x]  Skapa komponentklasser
- [x]  Skapa HTML-mallar för komponenter
- [x]  Implementera grundläggande CSS i projektet

**Definition of done:**

- [x]  CSS-filer implementerade i projektet
