### ISSUE TITLE
WebApp-Home: Som en användare vill jag kunna länkas till min varukorg

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#9]
**Tasks:** 
- [x] WebApp-Home: Integrera den designade varukorg ikonen i webbsidans header.
- [x] WebApp-Home: Använd en länk runt varukorg ikonen som navigerar till användarens varukorg när den klickas.
- [x] WebApp-Home: Utför tester för att säkerställa att ikonen fungerar korrekt och leder användaren till varukorgen.
- [x] WebApp-Home: Se till att varukorg ikonen och dess länk är responsiv och fungerar väl på både desktop och mobila enheter.
- [x] WebApp-Home: Implementera tillgänglighetsstandarder, såsom korrekt tabbordning.

**Definition of done**
- [x] Länk till varukorgen ska synas enligt designskiss och fungera.
